### ISSUE TITLE
Please provide downloadable ISOs

### ISSUE THREAD

**Issue by probonopd** [mbugni/centos-remix#1]
Please provide downloadable ISOs because the whole point of a Live ISO is that you don't have to install it.

You could use e.g., GitHub Actions to build the ISOs, and have them uploaded to GitHub Releases (given that they stay under a 2GB file size).

**Comment by mbugni** [comment]
Hi @probonopd, I'm going to clarify. Here there are some matters.

1. I don't want to provide something binary, but rather to show how to get it. I want to avoid repetitive post-install tasks on each new instance. Once you get the desired result, you can share it with people around you (parents, friends, colleagues, etc).
Italian support and a predefined collection of software are my personal goals, like the Fedora counterpart [1].

2. The automation is not trivial, because you need first to use virtualization to get the boot .iso by using Lorax. I don't know if it can be obtained outside the original OS, but I never investigated due to (1).

3. A general purpose downloadable .iso should be provided by the project maintainers, just like in the past. If they don't care, maybe is not a goal for them. Honestly it's not a goal for me.

[1] https://github.com/mbugni/fedora-remix

**Comment by mbugni** [comment]
From time to time I'll upload some `.iso` images, just for testing purpose. Take a look at [Releases](https://github.com/mbugni/centos-remix/releases) area.
